name: Publish
on:
  release:
    types: [published]
jobs:
  check:
    name: Check release info
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && contains(github.ref, '@v')
    outputs:
      package: ${{steps.info.outputs.package}}
    steps:
      - id: info
        run: |
          package="$(echo '${{github.ref}}' | sed 's/refs\/tags\///' | sed 's/@.*//')" &&
          echo "::set-output name=package::$package"
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: check
    steps:
      - run: cd "${{needs.check.outputs.package}}" && echo "Publish $(pwd)"
