name: Publish
on:
  release:
    types: [published]
jobs:
  check:
    name: Check release info
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && contains(github.ref, '@v')
    outputs:
      package: ${{steps.info.outputs.package}}
    steps:
      - id: info
        run: |
          package="$(echo '${{github.ref}}' | sed 's/refs\/tags\///' | sed 's/@.*//')" &&
          echo "::set-output name=package::$package" &&
          echo "Detected package $package"
  publish:
    name: Prepare code and publish
    runs-on: ubuntu-latest
    needs: check
    defaults:
      run:
        working-directory: ${{needs.check.outputs.package}}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run --if-present lint
      - run: npm run --if-present test
      - run: npm run --if-present build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
