name: x-up checks
on:
  push:
    branches: ["**"]
    paths:
      - "x-up/**"
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: "./*"
          key: ${{ github.sha }}
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - run: cd x-up && npm ci
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v2
        with:
          path: "./*"
          key: ${{ github.sha }}
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - run: cd x-up && npm run --if-present lint
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v2
        with:
          path: "./*"
          key: ${{ github.sha }}
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - run: cd x-up && npm run --if-present test
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/cache@v2
        with:
          path: "./*"
          key: ${{ github.sha }}
      - uses: actions/setup-node@v2
        with:
          node-version: "15"
      - run: cd x-up && npm run --if-present build
